export const SESSION_FETCHED = 'SESSION_FETCHED';
export const MOVIES_FETCHED = 'USER_MOVIES_FETCHED';
export const MOVIE_ADDED = 'USER_MOVIE_ADDED';
export const MOVIE_REMOVED = 'USER_MOVIE_REMOVED';
export const USER_FETCHED = 'USER_FETCHED';